name: "nexdrive-prod"

services:
  nexdrive-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - nexdrive-app
    networks:
      - nexdrive-net

  nexdrive-app:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    env_file: .env
    depends_on:
      nexdrive-db:
        condition: service_healthy
    networks:
      - nexdrive-net


  nexdrive-db:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo-prod-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - nexdrive-net

networks:
  nexdrive-net:

volumes:
  mongo-prod-data: