import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ProviderRedux } from "@/redux/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FileManager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body
        className={`flex relative flex-col lg:flex-row h-full min-h-screen w-full ${inter.className} antialiased`}
      >
        <ProviderRedux>{children}</ProviderRedux>
      </body>
    </html>
  );
}
